### PR TITLE
Simplify some CLDR pattern methods

### PR DESCRIPTION
**Pull request by JRaspass**
The right hand side of `@patterns` can be either a subref or a method name, either way it'll be invoked as a method. By just using the method name where we can we avoid one level of indirection. Subclassing is unaffected.

### CODE REVIEW

**Comment by JRaspass** [comment]
To be clear, the calling code does:
```perl
my $sub = $patterns[ $i + 1 ];

return $self->$sub();
```
So `$sub` can be either a subref of a method name string, we already use the latter in a couple of places and it avoids one extra layer of stack. This is the best kind of µoptimisation as it also makes the code simpler to read (IMO).

**Comment by autarch** [comment]
Thanks for this! This looks like a great improvement.

I'm pretty finicky about my projects (see [this blog post](https://blog.urth.org/2022/07/02/what-s-the-right-way-to-merge-a-pull-request/) for details), so I rarely merge a PR as-is. I can move forward on your PR in one of two ways:

1. I check it out locally, fiddle with it as needed, merge it locally, and simply close this PR. This will preserve at least one commit with your name on it, but the PR will show up as closed in your GitHub stats.
2. If you enable me to push directly to your fork, I can do my fiddling, then force push to your fork and merge the resulting PR. Again, this will preserve at least one commit with your name on it, but you _also_ get credit for the PR merge in your GitHub stats. The only downside is that I will be force pushing directly to your fork.

Please let me know which approach you'd prefer. If I don't hear from you before I get around to working on this PR I'll go with option #1.

Thanks again for your contribution!

**Comment by JRaspass** [comment]
I presume option two requires the "Allow edits by maintainers" option checked, which I have. So use whichever approach you prefer. I'm really not fussed about credit either way, I was just trying to squeeze a little performance out of CLDR formatting at $work and this seemed like an easy, albeit tiny win.

**Comment by autarch** [comment]
It wouldn't let me push to your fork, so I ended up merging this from the CLI. Thanks again!

**Pull request closed without merging**
