### PR TITLE
Add support for truncate(to=>'quarter')

### PR DESCRIPTION
**Pull request by nrdvana**

### CODE REVIEW

**Comment by autarch** [comment]
Thanks! This could really use a test though.

**Comment by nrdvana** [comment]
Sorry for the delay, I meant to make this part of the pull-request event Weds evening, but had a work emergency get in the way.  Testcase was certainly needed, because I forgot to update the validation regex :-)

**Comment by nrdvana** [comment]
Well I gave it a run through perltidy, but there's still something off with one of the author tests.  Do you mind taking it from here?

**Comment by autarch** [comment]
Yes, I can take it from here. Thanks.

**Comment by autarch** [comment]
I merged this from the CLI. Thanks.

**Comment by nrdvana** [comment]
Thanks so much!  (I've banged out the formula for quarter truncation an embarrassing number of times in my code up til now...)

**Pull request closed without merging**
