### PR TITLE
Add an rfc3339 method

### PR DESCRIPTION
**Pull request by autarch**

### CODE REVIEW

**Review by worthmine — CHANGES_REQUESTED** [review]
I much prefer to be able to omit `set_time_zone()` every each times rather than this.

how about like that?

```diff
sub rfc3339 {
-    my $self = shift;
+    my $self      = shift;
+    my %args      = @_ if @_ >= 2;
+    my $time_zone = shift;
+    $time_zone = $args{'time_zone'} if exists $args{'time_zone'};
+
+    return $self->datetime('T') . $self->_offset_as_string() unless defined $time_zone;
 
-    my $secs = $self->offset;
-    my $offset
-        = $secs
+    my $withTZ = $self->clone->set_time_zone($time_zone);
+    return $withTZ->datetime('T') . $withTZ->_offset_as_string();
+}
+
+sub _offset_as_string {
+    my $secs = $_[0]->offset();
+    return $secs
         ? DateTime::TimeZone->offset_as_string( $secs, q{:} )
         : 'Z';
-
-    return $self->datetime('T') . $offset;
 }
```
The purpose of this diff is that:
Even assuming that the default is UTC, it is easier to handle if we can retrieve as local time.
How to use is like below:

```perl
use strict;
use warnings;
use lib 'lib';

use DateTime;
use Time::Piece;
use feature qw(say);
use Data::ULID qw(ulid ulid_date);

say "--- with UTC ---";
say my $dt = DateTime->from_epoch( epoch => time() ), " <= from_epoch()";
say DateTime->now(), " <= now()";
say $dt->rfc3339(),  " <= rfc3339()";

say "--- with time zone ---";
my $t = Time::Piece->new;
say $dt = DateTime->from_epoch( epoch => $t->localtime->epoch(), time_zone => 'Asia/Tokyo' ),
    " <= from_epoch()";
say $dt = DateTime->now( time_zone => 'Asia/Tokyo' ), " <= now( time_zone => 'Asia/Tokyo' )";
say $dt->rfc3339(), " <= rfc3339()";

say "--- with using Data::ULID ---";
my $ulid = ulid();
say $dt = ulid_date($ulid), " <= by default";
say $dt->rfc3339(), " <= rfc3339() with default";
say $dt->rfc3339("UTC"), " <= rfc3339() with UTC";
say $dt->rfc3339( time_zone => 'Asia/Tokyo' ), " <= rfc3339() with temporal local time zone";
say $dt->rfc3339('America/Chicago'), " <= rfc3339() with omitted params";
say $dt->rfc3339(), " <= rfc3339() default \$dt is not affected";
```

this code returns that:

```
--- with UTC ---
2020-11-07T04:56:19 <= from_epoch()
2020-11-07T04:56:19 <= now()
2020-11-07T04:56:19Z <= rfc3339()
--- with time zone ---
2020-11-07T13:56:19 <= from_epoch()
2020-11-07T13:56:19 <= now( time_zone => 'Asia/Tokyo' )
2020-11-07T13:56:19+09:00 <= rfc3339()
--- with using Data::ULID ---
2020-11-07T04:56:19 <= by default
2020-11-07T04:56:19Z <= rfc3339() with default
2020-11-07T04:56:19Z <= rfc3339() with UTC
2020-11-07T13:56:19+09:00 <= rfc3339() with temporal local time zone
2020-11-06T22:56:19-06:00 <= rfc3339() with omitted params
2020-11-07T04:56:19Z <= rfc3339() default $dt is not affected
```

**Comment by autarch** [comment]
> I much prefer to be able to omit `set_time_zone()` every each times rather than this.

This would make this one method different from every other get method in the API, so I don't think this is a great idea.

**Comment by worthmine** [comment]
I'm sorry to be late again.

I think this is enough because you've wrote the method as I hope.

**Review by worthmine — APPROVED** [review]
It works like as I thought. 

thank you very much.

**Review by n1vux — APPROVED** [review]

**Comment by oschwald** [comment]
It might be nice if this included the fractional part on dates with sub-second resolution.

**Comment by autarch** [comment]
@oschwald Yes, good idea. A PR would be welcome.

**Pull request merged**
